#!/usr/bin/env bash
# Embed every file under ui/app/ into build/generated/static_assets.c.
# Usage: scripts/embed/gen-static-assets.sh > build/generated/static_assets.c
#
# We use `xxd -i` (macOS + Linux). Symbol names come from the path
# relative to ui/app/, with non-alphanumeric bytes mapped to '_'.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
WEB="$ROOT/ui/app"

cat <<'EOF'
/* Auto-generated by scripts/embed/gen-static-assets.sh. Do not edit. */

#include "static_assets.h"
#include <string.h>

EOF

if [ ! -d "$WEB" ]; then
    cat <<'EOF'
const pin_static_file pin_static_files[] = { {0,0,0,0} };
const size_t pin_static_count = 0;
const pin_static_file *pin_static_lookup(const char *path) { (void)path; return NULL; }
EOF
    exit 0
fi

declare -a paths cts syms
i=0
while IFS= read -r f; do
    rel="${f#$WEB/}"
    sym=$(printf 'pin_static_%s' "$rel" | tr -c 'A-Za-z0-9_' '_')
    case "$rel" in
        *.html) ct="text/html; charset=utf-8" ;;
        *.css)  ct="text/css; charset=utf-8" ;;
        *.mjs)  ct="application/javascript; charset=utf-8" ;;
        *.js)   ct="application/javascript; charset=utf-8" ;;
        *.wasm) ct="application/wasm" ;;
        *.svg)  ct="image/svg+xml" ;;
        *.png)  ct="image/png" ;;
        *.ico)  ct="image/x-icon" ;;
        *.json) ct="application/json" ;;
        *)      ct="application/octet-stream" ;;
    esac
    (cd "$(dirname "$f")" && xxd -i "$(basename "$f")") \
        | sed -E \
            -e "s/^unsigned char [[:alnum:]_]+\\[\\]/static const unsigned char ${sym}[]/" \
            -e "/^unsigned int [[:alnum:]_]+_len/d"
    if [ "$rel" = "index.html" ]; then
        paths[$i]="/"
    else
        paths[$i]="/$rel"
    fi
    cts[$i]="$ct"
    syms[$i]="$sym"
    i=$((i + 1))
done < <(find "$WEB" -type f | sort)

echo
echo "const pin_static_file pin_static_files[] = {"
for n in "${!syms[@]}"; do
    printf '    {"%s", "%s", %s, sizeof(%s)},\n' \
        "${paths[$n]}" "${cts[$n]}" "${syms[$n]}" "${syms[$n]}"
done
echo "};"
echo "const size_t pin_static_count = sizeof(pin_static_files) / sizeof(pin_static_files[0]);"
echo
cat <<'EOF'
const pin_static_file *pin_static_lookup(const char *path) {
    if (!path) return NULL;
    for (size_t i = 0; i < pin_static_count; i++) {
        if (!strcmp(pin_static_files[i].path, path)) return &pin_static_files[i];
    }
    return NULL;
}
EOF
